# Generated by Django 3.1.5 on 2021-04-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PagosListado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPago', models.CharField(max_length=100, verbose_name='Id')),
                ('emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de emision')),
                ('motivo', models.CharField(max_length=200, verbose_name='Motivo del Pago')),
                ('cantidad', models.CharField(max_length=200, verbose_name='Monto del Pago')),
                ('contenido', models.TextField(verbose_name='Descripcion')),
                ('fechaPagoExitoso', models.DateTimeField(auto_now=True, verbose_name='Fecha de pago exitoso')),
            ],
            options={
                'verbose_name': 'lista de pagos',
                'verbose_name_plural': 'lista de pagos',
                'ordering': ['-emision'],
            },
        ),
    ]
