# Generated by Django 3.1.5 on 2021-04-12 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagoslistado',
            options={'ordering': ['-emision'], 'verbose_name': 'lista de pagos'},
        ),
    ]
