# Generated by Django 3.1.5 on 2021-04-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_auto_20210412_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagosSolicitado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPago', models.CharField(max_length=100, verbose_name='Id')),
                ('emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de emision')),
                ('motivo', models.CharField(max_length=200, verbose_name='Motivo del Pago')),
                ('cantidad', models.CharField(max_length=200, verbose_name='Monto del Pago')),
                ('contenido', models.TextField(verbose_name='Descripcion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Pagos solicitados',
                'ordering': ['-emision'],
            },
        ),
        migrations.DeleteModel(
            name='PagosListado',
        ),
    ]
