# Generated by Django 3.1.5 on 2021-04-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_auto_20210413_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagosListado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de emision')),
                ('alias', models.CharField(max_length=200, verbose_name='Motivo del Pago o alias')),
                ('cantidad', models.CharField(max_length=200, verbose_name='Monto que se paga')),
                ('content', models.TextField(verbose_name='Descripcion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Lista de pagos que puede realizar un usuario',
                'ordering': ['-created'],
            },
        ),
    ]
