# Generated by Django 3.1.5 on 2021-04-15 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0006_registrado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagossolicitado',
            old_name='idPago',
            new_name='refpago',
        ),
    ]
