# Generated by Django 3.1.5 on 2021-04-15 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0007_auto_20210415_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagossolicitado',
            old_name='contenido',
            new_name='descripcion',
        ),
    ]
