# Generated by Django 3.1.5 on 2021-04-16 01:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0008_auto_20210415_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagossolicitado',
            name='id',
        ),
        migrations.AlterField(
            model_name='pagossolicitado',
            name='refpago',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Fecha de emision'),
        ),
    ]
