# Generated by Django 3.1.5 on 2021-04-16 01:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0010_auto_20210415_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagossolicitado',
            name='refpago',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Rerencia de Pago'),
        ),
    ]
