# Generated by Django 3.1.5 on 2021-04-16 04:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0011_auto_20210415_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoSolicitado',
            fields=[
                ('refpago', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Rerencia de Pago')),
                ('emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de emision')),
                ('motivo', models.CharField(max_length=200, verbose_name='Motivo del Pago')),
                ('cuatrimestre', models.CharField(blank=True, max_length=200, verbose_name='Cuatrimestre al que corresponde el adeudo')),
                ('fpago', models.CharField(max_length=200, verbose_name='Forma de Pago')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('beca', models.CharField(max_length=200, verbose_name='Beca aplicable')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Pagos solicitados',
                'ordering': ['-emision'],
            },
        ),
        migrations.DeleteModel(
            name='PagosSolicitado',
        ),
        migrations.DeleteModel(
            name='Registrado',
        ),
    ]
