# Generated by Django 3.1.5 on 2021-04-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0012_auto_20210415_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagosolicitado',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='pagosolicitado',
            name='fpago',
            field=models.CharField(max_length=200, verbose_name='Beca aplicable'),
        ),
    ]
