# Generated by Django 3.1.5 on 2021-04-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0014_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagosolicitado',
            name='descripcion',
            field=models.TextField(verbose_name='SDescripcion'),
        ),
        migrations.AlterField(
            model_name='pagosolicitado',
            name='fpago',
            field=models.CharField(max_length=200, verbose_name='Forma de pago'),
        ),
        migrations.AlterField(
            model_name='pagosolicitado',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes', verbose_name='Comprobante'),
        ),
    ]
