# Generated by Django 3.1.5 on 2021-04-22 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0015_auto_20210421_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagosolicitado',
            name='cantidad',
            field=models.IntegerField(default=100, verbose_name='cantidad a pagar'),
        ),
    ]
